package com.nextdoor.nextdoor.domain.rental.domain;

public enum RentalStatus {
    CREATED,
    BEFORE_PHOTO_ANALYZED,
    REMITTANCE_REQUESTED,
    REMITTANCE_CONFIRMED,
    RENTAL_PERIOD_ENDED,
    BEFORE_AND_AFTER_COMPARED,
    DEPOSIT_REQUESTED,
    RENTAL_COMPLETED,
    CANCELLED
}
