package com.nextdoor.nextdoor.domain.rental.domain;

public enum RentalStatus {
    CREATED,
    BEFORE_PHOTO_REGISTERED,
    REMITTANCE_REQUESTED,
    REMITTANCE_CONFIRMED,
    RENTAL_PERIOD_ENDED,
    AFTER_PHOTO_REGISTERED,
    DEPOSIT_REQUESTED,
    RENTAL_COMPLETED,
    CANCELLED
}
