spring:
  application:
    name: nextdoor

  transaction:
    default-timeout: 100

  datasource:
    hikari:
      maximum-pool-size: 10
      idle-timeout: 600000
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true

  cassandra:
    contact-points: nextdoor-cassandra #localhost:9042
    port: 9042
    keyspace-name: nextdoor_chat
    local-datacenter: datacenter1
    #    schema-action: CREATE_IF_NOT_EXISTS #테이블 없으면 엔티티보고 자동 생성

  rabbitmq:
    host: nextdoor-rabbitmq
    port: 5672

server:
  port: 8081

custom:
  google:
    ai:
      gemini:
        model: gemini-2.0-flash-001
        location: us-central1
  prompt-location: damageAnalyzerPrompt.txt

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: oneders