spring:
  application:
    name: nextdoor

  transaction:
    default-timeout: 100

  datasource:
    hikari:
      maximum-pool-size: 10
      idle-timeout: 600000
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      continue-on-error: false
      separator: ;

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true
    show-sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  cassandra:
    contact-points: localhost #localhost:9042
    port: 9042
    keyspace-name: nextdoor_chat
    local-datacenter: datacenter1

  rabbitmq:
    host: localhost
    port: 5672

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me

server:
  port: 8081

custom:
  google:
    ai:
      gemini:
        model: gemini-2.0-flash-001
        location: us-central1
  damage-analyzer-prompt-location: damageAnalyzerPrompt.txt
  damage-comparator-prompt-location: damageComparatorPrompt.txt

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: oneders